### ISSUE TITLE
Use PostCSS 5 API

### ISSUE THREAD

**Issue by TrySound** [robwierzbowski/node-pixrem#35]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by ai** [comment]
Any updates?

**Comment by callumacrae** [comment]
Welp, I want to use this module but I can't, because it's too inefficient right now :/ I'm already using other stuff with postcss, and I don't want to parse it, run some things on it, turn it back into CSS, and then parse it again to use this!

Is that what this issue is about? Would be good to have it as an actual postcss plugin.

**Comment by seaneking** [comment]
+1 for actual postcss plugin

**Comment by callumacrae** [comment]
Is there any way I can help with this? We've been waiting a couple months to use this library, but the performance impact right now would be too much, because we're already using autoprefixer.

**Comment by iamvdo** [comment]
Fixed in pixrem@3.0.0
