### ISSUE TITLE
How to add this to my site

### ISSUE THREAD

**Issue by hannieDaat** [robwierzbowski/node-pixrem#58]
Hi,
I would like to use the pixrem plugin, but I don't know how to use it.
My site is on Wordpress, with Sage child theme, and I'm using jQuery and not any other .js library. There is an error pointing at the first line of the code that I duplicated from the example of pixrem:

```
var fs      = require('fs');
var pixrem  = require('pixrem');
var postcss = require('postcss');

var css = fs.readFileSync('main.css', 'utf8');
var processedCss = postcss([pixrem]).process(css).css;

fs.writeFile('main.with-fallbacks.css', processedCss, function (err) {
  if (err) {
    throw err;
  }
  console.log('IE8, you\'re welcome.');
});
```

 I uploaded pixrem.js to my site. Is there any js file that I have to upload?

Many thanks in advance!
Hannie

**Comment by iamvdo** [comment]
Pixrem is designed to be used server-side, like all PostCSS modules. You shoud not use it on client side.
Basically, PostCSS is a tool that transforms your CSS during development. It is a node.js based app, that's why you have to use JavaScript.
So, to use Pixrem:
- Install node.js, PostCSS, configure and compile files you need
- Or, much simpler way, use an online tool like http://pleeease.io/play/ (pixrem is already bundled) where you copy-paste your CSS and get a new CSS.
